### ISSUE TITLE
Error: package or namespace load failed for ‘lazyeval’ in FUN(X[[i]], ...)

### ISSUE THREAD

**Issue by romanhaa** [hadley/lazyeval#97] opened 2017-05-05 14:15 UTC
When trying to install lazyeval, it is compiled without errors, but afterwards it doesn’t pass the R tests for proper installation. I could imagine that it is perhaps not compiled correctly but somehow good enough to not fail the test, would that be possible? Since I’m working on a poorly maintained cluster at work and don’t have root privileges on our system, I had to manually adjust the available compilers in …/etc/Makeconf. As you can see, currently it is set to use g++-4.9, but changing it to something else (i.e. gcc-x.x) didn’t help.

Here is the error log:

```
* installing *source* package ‘lazyeval’ ...
** package ‘lazyeval’ successfully unpacked and MD5 sums checked
** libs
g++-4.9 -I.../R-3.4.0/include -DNDEBUG   -I.../packages/include   -fpic  -I.../packages/include  -c expr.c -o expr.o
g++-4.9 -I.../R-3.4.0/include -DNDEBUG   -I.../packages/include   -fpic  -I.../packages/include  -c interp.c -o interp.o
g++-4.9 -I.../R-3.4.0/include -DNDEBUG   -I.../packages/include   -fpic  -I.../packages/include  -c lazy.c -o lazy.o
g++-4.9 -I.../R-3.4.0/include -DNDEBUG   -I.../packages/include   -fpic  -I.../packages/include  -c name.c -o name.o
g++-4.9 -I.../R-3.4.0/include -DNDEBUG   -I.../packages/include   -fpic  -I.../packages/include  -c utils.c -o utils.o
g++-4.9 -shared -L.../R-3.4.0/lib -L.../packages/lib -o lazyeval.so expr.o interp.o lazy.o name.o utils.o -L.../R-3.4.0/lib -lR
installing to .../R-3.4.0/library/lazyeval/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘lazyeval’ in FUN(X[[i]], ...):
 no such symbol env in package .../R-3.4.0/library/lazyeval/libs/lazyeval.so
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘.../R-3.4.0/library/lazyeval’
```

And here is some information of my setup:

```
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 7 (wheezy)

Matrix products: default
BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] colorout_1.1-2

loaded via a namespace (and not attached):
[1] compiler_3.4.0 tools_3.4.0
```

Does anyone have an idea what this could be caused by?

Any help is appreciated!

**Comment by lionel-** [comment] 2017-05-05 14:19
duplicate of https://github.com/hadley/lazyeval/issues/84

**Comment by lionel-** [comment] 2017-05-05 14:23
oops maybe that's because of the new registration system?

**Comment by romanhaa** [comment] 2017-05-08 14:25
I don't know what the problem was, but I suspect it has to do with the compilation. I switched to another node of our cluster and there the installation worked without errors. 

¯\_(ツ)_/¯

**Comment by vspinu** [comment] 2017-10-01 16:24
I was seeing this with lubridate when using an explicit dynlib declarations like `@useDynLib lubridate, C_parse_period, .registration=TRUE`. So I switched to all-in-one `#' @useDynLib lubridate, .registration=TRUE` and warning went away. I think that's the intended usage.

**Closed** 2017-10-18 22:32 UTC
